//
// Created by lenovo on 2020/7/28.
//

#ifndef INC_3DS_PRINTER_WINDOWINFO_H
#define INC_3DS_PRINTER_WINDOWINFO_H

#define WINDOW_HEIGHT 600
#define WINDOW_WIDTH 600
#define WINDOW_MD_H WINDOW_HEIGHT/2
#define WINDOW_MD_W WINDOW_WIDTH/2

#endif //INC_3DS_PRINTER_WINDOWINFO_H
